services:
  postgres:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_DB: "snowpro.lesson.service"
      POSTGRES_USER: "room2"
      POSTGRES_PASSWORD: "room2Password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    command: 
      -c "max_connections=200"
      -c "shared_buffers=256MB"
    volumes:
      - snowprolessondb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d snowpro.lesson.service -U room2 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - snowpro_net

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: "snowpro@room2.com"
      PGADMIN_DEFAULT_PASSWORD: "room2Password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    restart: unless-stopped
    networks:
      - snowpro_net

volumes:
  snowprolessondb-data:
  pgadmin-data:

networks:
  snowpro_net: